name: CineTroupe
favicon: null
layout_spectrum: 1
typography_spectrum: 0.40876
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0f141e'
    - '#314759'
    - '#eff5f7'
    - '#6e94b0'
    - '#7b6d64'
  brandStrength: 0
  lightness: 0.75
  saturation: 0
  rhythmicContrast: 1
purpose: []
